version: "3.8"

services:
  hardhat:
    image: node:16
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - "8545:8545"
    command: sh -c "npm install --verbose && npx hardhat node"
